[features]
seeds = false
[programs.localnet]
elearn = "9UZhEPPrzXSAScvZ2cDF1GgYGJTZrAcPUEwNGLvvu9Pr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/vincentleow/.config/solana/jake.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
